#!/bin/bash

set -e

VERSION=$(cat Dockerfile | grep '^ENV ELASTICSEARCH_VERSION' | cut -d" " -f3)
TAGS=($VERSION 7)

for TAG in "${TAGS[@]}"; do
  echo "===> Tagging $IMAGE_NAME as $DOCKER_REPO:x-pack-$TAG"
  docker tag $IMAGE_NAME $DOCKER_REPO:x-pack-$TAG
  echo "===> Pushing $DOCKER_REPO:x-pack-$TAG"
  docker push $DOCKER_REPO:x-pack-$TAG
done